site_name: Fivuvuv's note
repo_url: https://github.com/2333qbyqby/new-public-note.git
repo_name: 2333qbyqby/new-public-note
nav:
theme:
  name: 'material'
  logo: images/hinalogo.jpg
  favicon: images/hinalogo.jpg
  font: 
    text: Lato
  palette:
    #primary: black
  - media: "(prefers-color-scheme: light)" 
    scheme: default  #配色方案：浅色模式
    primary: black  #原色，默认蓝，用于标题、侧边栏、文本链接和其他几个组件
    accent: black  #强调色，默认蓝，可以交互的元素如悬停链接、按钮和滚动条
    toggle:
      icon: material/weather-sunny #图标，太阳
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"  
    scheme: slate  #配色方案：深色模式
    toggle:
      icon: material/weather-night  #图标，月亮
      name: Switch to light mode
plugins:
  - search
  - awesome-pages